### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by sk918** [sk918/protospace-34510#1]
# URL
https://protospace-34510.herokuapp.com/

**Comment by takumi0530** [comment]
@sk918 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**

- [x] **ログアウト状態のユーザーは、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページ以外のページに遷移しようとすると、ログインページにリダイレクトされること**
現状、ログアウト状態で投稿ページのURLを直接打ち込むと、投稿ページに遷移できてしまいます。


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by sk918** [comment]
@takumi0530 さん
ご確認いただきましてありがとうございます！
上記内容を修正し、ログアウト状態で新規投稿ページにアクセスしてもログイン画面が表示されるようにしました。
再度ご確認をお願いします。
お手数をおかけしますがよろしくお願い致します。

**Comment by takumi0530** [comment]
@sk918 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
